name: ğŸ§ª Run CI before merge

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - labeled
      - review_requested
      - ready_for_review
      - synchronize

concurrency:
  group: pr-check-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  linter:
    name: Check Linter
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3
      - name: âš™ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: âš™ï¸ Setup Melos
        run: dart pub global activate melos 2.9.0
      - name: âš™ï¸ Install dependencies for all packages
        run: melos run build:pub_get:all
      - name: ğŸ§ª Check linter and code quality
        run: |
          melos run quality:analyze:all
          melos run quality:dcm-checks:all

  test:
    name: Running Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3
      - name: âš™ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: âš™ï¸ Setup Melos
        run: dart pub global activate melos 2.9.0
      - name: âš™ï¸ Install dependencies for all packages
        run: melos run build:pub_get:all
      - name: ğŸ§ª Run unit tests
        run: melos run test:all

  title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}